name: UnitTests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout path-translator repo
        uses: actions/checkout@v4
        with:
          path: path-translator

      - name: Checkout roblox-ts repo
        uses: actions/checkout@v4
        with:
          repository: roblox-ts/roblox-ts
          path: roblox-ts

      - name: Install Foreman
        uses: Roblox/setup-foreman@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup path-translator repo
        run: |
          cd path-translator
          npm install
          npm run build

      - name: Setup roblox-ts repo
        run: |
          cd roblox-ts
          foreman install
          npm install
          npm install ../path-translator
          npm run update-test-types

      - name: Run Tests
        run: |
          cd roblox-ts
          npm test
